#----------------------------------------------------
#                     MINIO
#----------------------------------------------------
minio:
  image:
    repository: "minio/minio"
    tag: "RELEASE.2024-01-18T22-51-28Z"
  replicas: 1
  accessKeyId: "admin"
  secretAccessKey: "60241594"
  tolerations:
    notReady: 20
    unreachable: 20
  persistence:
    size: "5Gi"
    storageClassName: "longhorn"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  ingress:
    enabled: true
    host: "minio.pcs.ui"
    className: "nginx"

#----------------------------------------------------
#                        LOKI
#----------------------------------------------------
loki:
  replicas: 3
  servicePort: 3100
  image:
    tag: "3.0.0"
  s3:
    bucketName: "loki-data"
    accessKeyId: "admin"
    secretAccessKey: "60241594"
  pvc:
    storageClassName: "longhorn"
    size: "5Gi"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

#----------------------------------------------------
#                      MIMIR
#----------------------------------------------------
mimir:
  replicas: 2
  servicePort: 9009
  multitenancy:
    enabled: false
  ingester:
    replicationFactor: 2
  storeGateway:
    replicationFactor: 2
  image:
    tag: "2.0.0"
    pullPolicy: "IfNotPresent"
  s3:
    bucketName: "mimir-data"
    accessKeyId: "admin"
    secretAccessKey: "60241594"
  pvc:
    storageClassName: "longhorn"
    size: "5Gi"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

#----------------------------------------------------
#                      TEMPO
#----------------------------------------------------
tempo:
  replicas: 2
  servicePort: 3200
  retention: "48h"
  multitenancy:
    enabled: false
  image:
    tag: "2.0.0"
    pullPolicy: "IfNotPresent"
  s3:
    bucketName: "tempo-data"
    accessKeyId: "admin"
    secretAccessKey: "60241594"
  storage:
    size: "5Gi"
    className: "longhorn"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  

#----------------------------------------------------
#                  GRAFANA DATABASE
#----------------------------------------------------
database:
  clusterName: "grafana-db-cluster"
  name: "grafana"
  user: "grafana"
  password: "grafanadbpassword123"
  instances: 3
  tolerationSeconds: 60
  storageSize: "5Gi"
  storageClassName: "longhorn"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
  affinityType: "preferred" 

#----------------------------------------------------
#                      GRAFANA
#----------------------------------------------------
grafana:
  replicas: 1
  service:
    type: ClusterIP
  image:
    repository: "grafana/grafana"
    tag: "13.1.0"
    pullPolicy: "IfNotPresent"
  adminUser: "admin"
  adminPassword: "admin123"
  database:
    type: "postgres"
    sslMode: "disable"
  ingress:
    host: "grafana.pcs.ui"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"