apiVersion: v2
name: lgtm-stack
description: A complete Kubernetes observability stack with Grafana, Mimir, Loki, Tempo, Alloy, and MinIO
type: application
version: 0.1.2
appVersion: "1.16.0"
keywords:
  - monitoring
  - observability
  - grafana
  - loki
  - mimir
  - tempo
  - alloy
  - prometheus
home: https://github.com/lucifer3618/lgtm-stack
sources:
  - https://github.com/lucifer3618/lgtm-stack
maintainers:
  - name: Chathura Udayanga
    email: chathux3618@gmail.com
icon: https://lucifer3618.github.io/lgtm-stack/assets/logo.svg
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of lgtm-stack with Grafana, Mimir, Loki, Tempo, Alloy, and MinIO
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: monitoring-logging
  artifacthub.io/images: |
    - name: grafana
      image: grafana/grafana:13.1.0
    - name: mimir
      image: grafana/mimir:3.2.0
    - name: loki
      image: grafana/loki:3.7.6
    - name: tempo
      image: grafana/tempo:2.10.8
    - name: alloy
      image: grafana/alloy:v1.18.1
    - name: minio
      image: minio/minio:RELEASE.2024-01-18T22-51-28Z
  artifacthub.io/links: |
    - name: source
      url: https://github.com/lucifer3618/lgtm-stack
    - name: issues
      url: https://github.com/lucifer3618/lgtm-stack/issues
