apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-db-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.user | default "grafana" | quote }}
  password: {{ .Values.database.password | default "grafanadbpassword123" | quote }}