apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-minio-pvc"
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size | default "20Gi" }}
  storageClassName: {{ .Values.minio.persistence.storageClassName | default "longhorn" }}