apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-alloy"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http-internal
      port: 12345
      targetPort: 12345
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318