{{- if and .Values.tls.enabled .Values.tls.autoGenerateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName | default (printf "%s-tls" (include "monitoring-stack.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tls-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}