apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-tempo-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  accessKeyId: {{ .Values.tempo.s3.accessKeyId | quote }}
  secretAccessKey: {{ .Values.tempo.s3.secretAccessKey | quote }}