apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    app: loki
spec:
  type: {{ .Values.loki.service.type | default "ClusterIP" }}
  {{- if .Values.loki.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loki.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      targetPort: 9095