apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Release.Name }}-loki-secret"
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
    S3_ACCESS_KEY_ID: "{{ .Values.loki.s3.accessKeyId | b64enc }}"
    S3_SECRET_ACCESS_KEY: "{{ .Values.loki.s3.secretAccessKey | b64enc }}"