apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-loki"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      targetPort: 9095